version: "3"

services:

  runtime-setup:
    image: swift-distributed-actors:20.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-focal"

  unit-tests:
    image: swift-distributed-actors:20.04-main
    environment:
      - EXPLICIT_TARGET_DEPENDENCY_IMPORT_CHECK=--explicit-target-dependency-import-check error

  unit-tests-until-failure:
    image: swift-distributed-actors:20.04-main

  integration-tests:
    image: swift-distributed-actors:20.04-main

  test:
    image: swift-distributed-actors:20.04-main
    environment:
      - EXPLICIT_TARGET_DEPENDENCY_IMPORT_CHECK=--explicit-target-dependency-import-check error

  bench:
    image: swift-distributed-actors:20.04-main

  shell:
    image: swift-distributed-actors:20.04-main
